version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
       POSTGRES_DB: 'clinic_db'
       POSTGRES_USER: 'spring'
       POSTGRES_PASSWORD: 'spring'

    ports:
      - '5434:5432'
