version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_DB: 'clinic_db'
      POSTGRES_USER: 'spring'
      POSTGRES_PASSWORD: 'spring'

    ports:
      - '5434:5432'

  db_test:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_DB: 'clinic_testdb'
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'

    ports:
      - '5535:5432'